# Generated by Django 5.0.4 on 2024-06-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("python_project_app", "0002_discount_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="client_photos", verbose_name="photo"
            ),
        ),
    ]
