# Generated by Django 5.0.4 on 2024-05-06 20:26

import datetime
import django.core.validators
import django.db.models.deletion
import python_project_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("python_project_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="end_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime.now,
                null=True,
                validators=[python_project_app.models.check_date],
                verbose_name="end date",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime.now,
                null=True,
                validators=[python_project_app.models.check_date],
                verbose_name="start date",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="title",
            field=models.TextField(
                blank=True, default="not title", max_length=250, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="marketplace",
            name="title",
            field=models.TextField(
                blank=True, max_length=250, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="marketplace",
            name="url_address",
            field=models.URLField(blank=True, null=True, verbose_name="url address"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="description",
            field=models.TextField(
                max_length=1000, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="rating",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="rating",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="title",
            field=models.TextField(blank=True, max_length=250, verbose_name="title"),
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        default=python_project_app.models.get_datetime,
                        null=True,
                        validators=[python_project_app.models.check_created],
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True,
                        default=python_project_app.models.get_datetime,
                        null=True,
                        validators=[python_project_app.models.check_modified],
                        verbose_name="modified",
                    ),
                ),
                (
                    "money",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=11,
                        validators=[python_project_app.models.check_positive],
                        verbose_name="money",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
                "db_table": '"online"."client"',
            },
        ),
        migrations.CreateModel(
            name="ShopToClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        default=python_project_app.models.get_datetime,
                        null=True,
                        validators=[python_project_app.models.check_created],
                        verbose_name="created",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="python_project_app.client",
                        verbose_name="client",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="python_project_app.shop",
                        verbose_name="shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "relationship shop client",
                "verbose_name_plural": "relationships shop client",
                "db_table": '"online"."shop_to_client"',
            },
        ),
        migrations.AddField(
            model_name="client",
            name="books",
            field=models.ManyToManyField(
                through="python_project_app.ShopToClient",
                to="python_project_app.shop",
                verbose_name="shops",
            ),
        ),
    ]
