# Generated by Django 5.0.4 on 2024-06-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("python_project_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="discount_images", verbose_name="image"
            ),
        ),
    ]
