# Generated by Django 5.0.4 on 2024-05-22 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("python_project_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="end_date",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start_date",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                null=True,
                verbose_name="start date",
            ),
        ),
    ]
