name: Тесты library_app
on: [push]
jobs:
  container-job:
    name: Тесты
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: admin123
          POSTGRES_DBNAME: project_python
          POSTGRES_USER: viktoria_2024
          POSTGRES_PORT: 5555
          POSTGRES_HOST: 127.0.0.1
        ports:
        - 5555:5432
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11.0"
    - name: Установка модулей и зависимостей
      run: |
        python -m pip install Pillow
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
    - name: Тесты models
      run: |
        chmod +x tests/test.sh
        ./tests/test.sh tests.test_models
    - name: Тесты views
      run: |
        chmod +x tests/test.sh
        ./tests/test.sh tests.test_views
    - name: Тесты api
      run: |
        chmod +x tests/test.sh
        ./tests/test.sh tests.test_api
    - name: Тесты forms
      run: |
        chmod +x tests/test.sh
        ./tests/test.sh tests.test_forms
    - name: Тесты profile
      run: |
        chmod +x tests/test.sh
        ./tests/test.sh tests.test_profile
    - name: Тесты remove discount
      run: |
        chmod +x tests/test.sh
        ./tests/test.sh tests.test_remove_discount